name: test-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          make install-deps

      - name: Build
        run: |
          make debug

      - name: Install Ceph
        run: |
          sudo ./ci/setup_ceph.sh
          sudo ceph osd pool create pone

      - name: Run tests
        run: |
          mkdir -p /mnt/lsvd
          
          cd build-dbg
          sudo meson test
          sudo ./imgtool create pone test-img --size 5g

      - name: Logs
        if: always()
        run: |
          cat build-dbg/meson-logs/*.txt
