name: test-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Clang 18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Install dependencies
        run: |
          sudo apt update
          make install-deps
          pip3 install --upgrade meson

      - name: Build
        run: |
          make debug

      - name: Install Ceph
        run: |
          sudo ./ci/setup_ceph.sh
          sudo ceph osd pool create pone

      - name: Run tests
        run: |
          mkdir -p /tmp/lsvd-read
          mkdir -p /tmp/lsvd-write
          
          cd build-dbg
          sudo meson test
          sudo ./imgtool --create --size 1g --pool pone test-img

      - name: Logs
        if: always()
        run: |
          cat build-dbg/meson-logs/meson-log.txt
